### ISSUE TITLE
Top level function expression need to be parenthesized

### ISSUE THREAD

**Issue by tolmasky** [estools/escodegen#222]
I'm actually not sure if this is the case, but this:

```javascript
(function() {})
```

certainly parses to:

Program { body: [ { ExpressionStatement { expression: FunctionExpression } }] }

However, that then code-gens:

function(){}

which is a syntax error (not longer a valid program since top level can't have floating unnamed functions). This used to work in 1.4.1 at least, but not in 1.6.0. To reproduce:

```javascript
escodegen.generate(acorn.parse("(function(){})"))
```

**Comment by tolmasky** [comment]
Sorry, forgot a key thing to replicate. This only happens with Async functions. So if FunctionExpression.async === true, then you get

async function() {}

instead of

(async function(){})

This worked in 1.4.1.

**Comment by Constellation** [comment]
@tolmasky:

Seeing the spec[1], I think

```js
async function(){}
```

is not a syntax error. So I think there's no need to parenthesize it.
Is  it correct?

[1]: https://github.com/lukehoban/ecmascript-asyncawait

**Comment by tolmasky** [comment]
6to5 certainly does not like an async function without parenthesis. Also, "function(){}" *is* a syntax error, so unless async function() {} has some sort of exception, I would expect it to be as well.

**Comment by michaelficarra** [comment]
It shouldn't be a syntax error because the first token is not the first token of any statement. See the lookahead restriction for the ExpressionStatement grammar production.

**Comment by Constellation** [comment]
Yes, `function(){}` is a syntax error.

But this is because when reading a token `function` in `Program` context, we cannot determine whether it's `FunctionExpression` or `FunctionDeclaration`.
As @michaelficarra described, it is standardized in [1].

But in the case of `async function(){}`, when `async` comes, we can determine the following is `Expression`. We can parse it as `async FunctionExpression`. So parentheses are not necessary.

[1]: http://ecma-international.org/ecma-262/5.1/#sec-12.4

**Comment by tolmasky** [comment]
So at the very least then it seems that the rewrite spec needs more consideration:

"
async function <name>?<argumentlist><body>
=>
function <name>?<argumentlist>{ return spawn(function*() <body>); }
"

That being said, I suppose I'll file this on Traceur and 6to5 instead.

**Comment by Constellation** [comment]
@tolmasky 

Ah! Good point. I missed it, thank you!

Seeing the spec, I've found that there's `AsyncFunctionDeclaration`.
Hm, in this case, we cannot determine
```
async function test() { }
```
is `AsyncFunctionExpression` or `AsyncFunctionDeclaration`.

First I thought `async function () {}` is valid because of the spec BNF. But considering the above case, now I suppose that the current spec has an issue about it.

@michaelficarra, what do you think about it?

**Comment by michaelficarra** [comment]
See my edit above. I came to the same conclusion.

**Comment by Constellation** [comment]
@michaelficarra Thank you!

@tolmasky :

Great! It's a spec & escodegen's bug.
I'd recommend you to file this in [1], it improves the ES7 spec!

And we need to fix it in escodegen!

[1]: https://github.com/lukehoban/ecmascript-asyncawait/issues

**Comment by Constellation** [comment]
Done. Thank you :)
This implementation will be improved when code generator with state is landed.

**Comment by Constellation** [comment]
Published as `1.6.1`.

**Comment by michaelficarra** [comment]
I've filed https://github.com/lukehoban/ecmascript-asyncawait/issues/28.

**Comment by Constellation** [comment]
@michaelficarra Great!
