### ISSUE TITLE
General way to customize code generation?

### ISSUE THREAD

**Issue by mark-hahn** [estools/escodegen#265]
Is there a discussion forum for escodegen newbies that need help?  I'll post my question here and delete it if there is a better place.

I am trying to generate code with a somewhat different syntax than JS.  The ultimate goal is a two-way translator that goes between normal JS syntax and one similar to Coffeescript.  It is *not* a different language like Coffeescript.  It is just changing things like `function` to/from `->` and significant whitespace.  If you are really bored you can check out [my project](https://github.com/mark-hahn/jsw) but this isn't needed for this question.

I'm starting with what I thought was the easiest part.  I'm just trying to change `function` to/from `->`.  I parsed JS with Acorn and then generated code with escodegen.  Apparently, to my surprise, the `verbatim` option can't do this, #264.

Can someone think of a way for me to do this other than forking escodegen?

**Comment by fabiosantoscode** [comment]
I've managed to bend the rules and hack my way around it and currently I'm using escodegen to output c++. I'm bad at explaining, my code is ugly because I'm not used to writing coffeescript, but please bear with me.

escodegen will let me print any javascript I give it if it's a Literal with a "raw" property. But first I had to go through [some "value" check I don't understand](https://github.com/estools/escodegen/blob/master/escodegen.js#L2280), so I hacked my way around it using a dummy object and always giving that same object as the "value" of the literal.

You can see the aforementioned hackery [here](https://github.com/fabiosantoscode/js2cpp/blob/master/gen.coffee).

But that still doesn't solve the problem of generating code recursively (for example, when something that looks like C, like "int main" has stuff that escodegen can actually do for me, like "2 + 6;". So I'm using estraverse.replace to navigate the syntax tree, replacing stuff with raw C code.

I do some of the recursion myself. For example, when I'm recursing into the program `function main() {return 2+6}` with estraverse, as soon as I see the function I have to return the whole string, even the parts that I'm trusting escodegen to do! That's when I have to recurse into myself. This means I have to return `"int main () {" + my_generator_again(theFunction.body) + "}"`.

To help illustrate my point, [here's what I'm talking about.](https://github.com/fabiosantoscode/js2cpp/blob/master/format.coffee#L88)

All of this basically means I'm not customizing escodegen, I'm just using it in short bursts instead of giving it a big object and wait for the result. But it's still tons better than to actually customize it, and if you get around the weirdness of this setup, it's really quite powerful.

In the context of escodegen, I think it would be possible to do something to help guys like you and me by providing some object like this: `{ type: "EscodegenWrapThisSubtree", before: "int main(){", after: "}", middle: restOfTree }` object, which I'm sure wouldn't fix all the use cases.

ps: If you go down this road, you'll like to know that VariableDeclaration can have any "kind" associated with it. `var`? `let`? `std::vector<std::vector<std::string>>`? escodegen don't care!

**Comment by mark-hahn** [comment]
Thanks very much.  That is impressive stuff.

I am only considering Javascript and I have discovered https://github.com/cst/cst which provides a CST instead of an AST.  The library in that repo actually replaces escodegen.  So I am moving to that which will give me very solid control over the output.
